# Generated by Django 4.2.20 on 2025-11-18 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the service (e.g., "Haircut", "Yoga Session")', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the service')),
                ('duration_minutes', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours'), (180, '3 hours')], default=60, help_text='Duration of the service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Your business or professional name', max_length=200)),
                ('business_type', models.CharField(choices=[('salon', 'Salon & Spa'), ('fitness', 'Fitness & Gym'), ('tutor', 'Tutoring & Education'), ('healthcare', 'Healthcare & Wellness'), ('other', 'Other Services')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of your services')),
                ('phone', models.CharField(help_text='Primary contact number', max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number for notifications (Pro plan only)', max_length=15)),
                ('business_address', models.TextField(blank=True, help_text='Full business address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('current_plan', models.CharField(choices=[('free', 'Free Plan'), ('pro', 'Pro Plan')], default='free', help_text='Current subscription plan', max_length=10)),
                ('plan_start_date', models.DateField(default=django.utils.timezone.now, help_text='Date when current plan started')),
                ('plan_end_date', models.DateField(blank=True, help_text='Plan expiry date (null for free plan or unlimited)', null=True)),
                ('trial_end_date', models.DateField(blank=True, help_text='14-day trial period end date', null=True)),
                ('is_trial_active', models.BooleanField(default=True, help_text='Whether the 14-day trial is active')),
                ('appointments_this_month', models.IntegerField(default=0, help_text='Number of appointments created this month')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Last date when monthly counter was reset')),
                ('unique_booking_url', models.SlugField(help_text='Unique URL slug for booking page (e.g., /book/your-salon)', max_length=100, unique=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Business logo or profile picture', null=True, upload_to='profile_images/')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the provider is verified by admin')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the provider account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the staff member', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address for notifications (optional)', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('bio', models.TextField(blank=True, help_text='Brief bio or description')),
                ('profile_image', models.ImageField(blank=True, help_text='Staff member photo', null=True, upload_to='staff_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this staff member is currently active')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display staff members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(help_text='The service provider this staff member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='providers.serviceprovider')),
                ('services', models.ManyToManyField(blank=True, help_text='Services this staff member can provide', related_name='staff_members', to='providers.service')),
                ('user', models.OneToOneField(blank=True, help_text='Optional: Link to user account for staff login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['display_order', 'name'],
                'unique_together': {('service_provider', 'email')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.serviceprovider'),
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Start time for this availability slot')),
                ('end_time', models.TimeField(help_text='End time for this availability slot')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the staff member is available on this day')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='providers.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Availability',
                'verbose_name_plural': 'Staff Availability Slots',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('staff_member', 'day_of_week')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('service_provider', 'service_name')},
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Opening time')),
                ('end_time', models.TimeField(help_text='Closing time')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the provider is available on this day')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability Slots',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('service_provider', 'day_of_week')},
            },
        ),
    ]
