# Generated by Django 4.2.20 on 2025-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain or subdomain (e.g., ramesh-salon.yourdomain.com or www.rameshsalon.com)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='custom_domain_type',
            field=models.CharField(choices=[('none', 'Default'), ('subdomain', 'Custom Subdomain'), ('domain', 'Custom Domain')], default='none', help_text='Type of custom domain configuration', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='domain_added_at',
            field=models.DateTimeField(blank=True, help_text='When the domain was added', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='domain_verification_code',
            field=models.CharField(blank=True, help_text='Random code for domain verification', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='domain_verified',
            field=models.BooleanField(default=False, help_text='Whether the domain has been verified'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='ssl_enabled',
            field=models.BooleanField(default=False, help_text='Whether SSL is enabled for the custom domain'),
        ),
    ]
