# Generated by Django 4.2.20 on 2025-11-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_serviceprovider_custom_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_trial_active',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='trial_end_date',
        ),
    ]
