# Generated by Django 4.2.20 on 2025-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_remove_serviceprovider_is_trial_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='accepting_appointments',
            field=models.BooleanField(default=True, help_text='Whether this provider is currently accepting new appointments'),
        ),
    ]
