# Generated by Django 4.2.20 on 2025-11-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_serviceprovider_accepting_appointments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Default Availability', 'verbose_name_plural': 'Default Availability'},
        ),
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Opening time for this service')),
                ('end_time', models.TimeField(help_text='Closing time for this service')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this service is available on this day')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_availability', to='providers.service')),
            ],
            options={
                'verbose_name': 'Service Availability',
                'verbose_name_plural': 'Service Availability',
                'ordering': ['service', 'day_of_week', 'start_time'],
                'unique_together': {('service', 'day_of_week')},
            },
        ),
    ]
