# Generated by Django 4.2.20 on 2025-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_availability_options_serviceavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='cname_target',
            field=models.CharField(blank=True, help_text='Unique CNAME target for this provider (e.g., provider-abc123.nextslot.in)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='txt_record_name',
            field=models.CharField(blank=True, default='_booking-verify', help_text='TXT record name for domain verification (e.g., _nextslot-verify-abc123)', max_length=255),
        ),
    ]
