# Generated by Django 4.2.20 on 2025-11-18 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client name (for walk-ins or override)', max_length=200)),
                ('client_phone', models.CharField(help_text='Client phone number', max_length=15)),
                ('client_email', models.EmailField(blank=True, help_text='Client email (optional for walk-ins)', max_length=254)),
                ('appointment_date', models.DateField(help_text='Date of appointment')),
                ('appointment_time', models.TimeField(help_text='Time of appointment')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total amount for the service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Card'), ('online', 'Online Payment')], help_text='Payment method used', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requests or notes')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder notification was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Registered client (null for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='providers.service')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='providers.serviceprovider')),
                ('staff_member', models.ForeignKey(blank=True, help_text='Staff member assigned to this appointment (PRO plan only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='providers.staffmember')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='appointment_appoint_c5b816_idx'), models.Index(fields=['service_provider', 'status'], name='appointment_service_d040bd_idx')],
            },
        ),
    ]
