# Generated by Django 4.2.20 on 2025-11-18 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name (e.g., "Free", "Pro")', max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free Plan'), ('pro', 'Pro Plan')], max_length=10, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_appointments_per_month', models.IntegerField(blank=True, help_text='Maximum appointments per month (null = unlimited)', null=True)),
                ('max_services', models.IntegerField(blank=True, help_text='Maximum number of services (null = unlimited)', null=True)),
                ('features', models.JSONField(default=dict, help_text='JSON object containing plan features')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=200)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscriptionplan')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='providers.serviceprovider')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
